/**
 * Space Highway — road + lane-dash art generator.
 *
 * Emits road.svg (the asphalt, its neon edge lines and the roadside terrain) and lanes-0..3.svg
 * (the centre dashes at four phases of one dash period) from ONE road-curve definition below.
 * Sits next to its output the way fx.ts sits next to fx.js and runic/runes.gen.js sits next to
 * its runes, and is never loaded by the app:  node aesthetics/spacehighway/road.gen.js
 *
 * Why generated:
 *  - The dashes have to land exactly on the road's centreline at every distance. Hand-authoring
 *    five files that share a curve guarantees drift, and drift here shows as dashes sliding off
 *    the tarmac.
 *  - The four lane phases must be the SAME dash pattern shifted by a quarter period, so the
 *    theme can cycle background-image through them with steps(1) and get marching dashes for
 *    four repaints a second instead of a repaint every frame. Phase 1.0 is phase 0.0 with every
 *    dash advanced one slot, which is what makes the loop seamless.
 *
 * Perspective: for a flat road, screen distance below the horizon is proportional to 1/world
 * distance, and so is the road's apparent width. So `t` (0 at the horizon, 1 at the bottom
 * edge) is linear in y AND proportional to half-width — one parameter drives both, and a dash
 * at world distance d simply sits at t = D_NEAR / d.
 */

const fs = require('fs');
const path = require('path');

// ---- The road, defined once ----
const W = 900, H = 1600;
const VPX = 520;          // vanishing point, x — right of centre so the view reads as a lane
const VPY = 618;          // vanishing point / horizon, y (38.6% down: sits in the windshield)
const HW_VP = 5;          // road half-width at the horizon (not zero, or it ends in a needle)
const HW_BOT = 640;       // road half-width at the bottom edge
const BEND_A = 140, BEND_B = 250;   // gentle S-bend: right of the VP at mid, back left at the bottom

const yAt = (t) => VPY + (H - VPY) * t;
const cxAt = (t) => VPX + BEND_A * t * t - BEND_B * t * t * t;
const hwAt = (t) => HW_VP + (HW_BOT - HW_VP) * t;

// ---- Dashes, in world space ----
const D_NEAR = 1;         // world distance that maps to t = 1 (the bottom edge)
const GAP = 0.34;         // spacing between dash starts, as a fraction of D_NEAR
const DASH = 0.155;       // dash length, same units — a little under half the gap
const T_MIN = 0.062;      // stop before the dashes smear into the vanishing point
const DASH_HW = 26;       // dash half-width at t = 1
const PHASES = 4;

const f = (n) => Number(n.toFixed(2));

/** Points down the left then back up the right of a band, sampled so the curve stays smooth. */
function band(t0, t1, halfWidthAt, steps = 12) {
  const left = [], right = [];
  for (let i = 0; i <= steps; i++) {
    const t = t0 + (t1 - t0) * (i / steps);
    const cx = cxAt(t), y = yAt(t), hw = halfWidthAt(t);
    left.push(`${f(cx - hw)},${f(y)}`);
    right.push(`${f(cx + hw)},${f(y)}`);
  }
  return left.concat(right.reverse()).join(' ');
}

/** One edge of the road as a tapering ribbon — a stroked path can't taper, so it's a polygon. */
function edge(side, widthAtBottom) {
  const pts = [];
  const back = [];
  const steps = 24;
  for (let i = 0; i <= steps; i++) {
    const t = i / steps;
    const cx = cxAt(t), y = yAt(t), hw = hwAt(t);
    const w = Math.max(0.6, widthAtBottom * t);
    const x = cx + side * hw;
    pts.push(`${f(x - w)},${f(y)}`);
    back.push(`${f(x + w)},${f(y)}`);
  }
  return pts.concat(back.reverse()).join(' ');
}

function lanesSvg(phase) {
  const quads = [];
  for (let n = 0; n < 60; n++) {
    const d0 = D_NEAR * (1 + (n + phase) * GAP);
    const d1 = d0 + D_NEAR * DASH;
    const tNear = D_NEAR / d0;      // the end closest to the viewer
    const tFar = D_NEAR / d1;
    if (tNear < T_MIN) break;
    if (tNear > 1) continue;        // already past the bottom edge
    quads.push(
      `<polygon points="${band(tFar, tNear, (t) => DASH_HW * t, 4)}"/>`
    );
  }
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by road.gen.js — do not edit. Lane dashes, phase ${phase}. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid slice">
  <defs>
    <linearGradient id="fade" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffffff" stop-opacity="0"/>
      <stop offset="0.10" stop-color="#ffffff" stop-opacity="0.7"/>
      <stop offset="1" stop-color="#ffffff" stop-opacity="1"/>
    </linearGradient>
    <mask id="m">
      <rect x="0" y="${VPY}" width="${W}" height="${H - VPY}" fill="url(#fade)"/>
    </mask>
  </defs>
  <g mask="url(#m)" fill="#f4fbff">
${quads.map((q) => '    ' + q).join('\n')}
  </g>
</svg>
`;
}

function roadSvg() {
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- GENERATED by road.gen.js — do not edit. Road surface, neon edges and roadside terrain.
     Baked sector-neutral (asphalt grey, white-neon edge lines): art referenced by url() can't
     see the page's custom properties, so the SECTOR hue is applied by theme.css as a bloom
     layered over this. See the header of theme.css. -->
<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" preserveAspectRatio="xMidYMid slice">
  <defs>
    <linearGradient id="ground" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#1b2331"/>
      <stop offset="0.35" stop-color="#111722"/>
      <stop offset="1" stop-color="#05070c"/>
    </linearGradient>
    <linearGradient id="tar" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#2b3340"/>
      <stop offset="0.45" stop-color="#20262f"/>
      <stop offset="1" stop-color="#161b22"/>
    </linearGradient>
    <linearGradient id="neon" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#ffffff" stop-opacity="0.25"/>
      <stop offset="0.18" stop-color="#ffffff" stop-opacity="0.95"/>
      <stop offset="1" stop-color="#ffffff" stop-opacity="1"/>
    </linearGradient>
    <filter id="bloom" x="-30%" y="-30%" width="160%" height="160%">
      <feGaussianBlur stdDeviation="9"/>
    </filter>
    <filter id="hillblur" x="-10%" y="-40%" width="120%" height="180%">
      <feGaussianBlur stdDeviation="3"/>
    </filter>
  </defs>

  <!-- Ground plane from the horizon down. Everything above ${VPY} stays transparent so the
       CSS star field and swirl are the sky. -->
  <rect x="0" y="${VPY}" width="${W}" height="${H - VPY}" fill="url(#ground)"/>

  <!-- Roadside headlands, low and dark, so the horizon isn't a bare ruled line (reference 2). -->
  <g fill="#0a1018" filter="url(#hillblur)">
    <path d="M -20 ${VPY + 4} L 120 ${VPY - 52} L 250 ${VPY - 22} L 372 ${VPY - 40} L 452 ${VPY + 2} Z"/>
    <path d="M 596 ${VPY + 2} L 690 ${VPY - 34} L 812 ${VPY - 58} L 920 ${VPY - 16} L 920 ${VPY + 6} Z"/>
  </g>

  <!-- Asphalt -->
  <polygon points="${band(0, 1, hwAt, 26)}" fill="url(#tar)"/>

  <!-- Neon edge lines: a blurred bloom pass under a crisp core, both tapering with distance.
       Baked white — theme.css lays the sector hue over the whole road area. -->
  <g opacity="0.55" filter="url(#bloom)" fill="#bfe8ff">
    <polygon points="${edge(-1, 16)}"/>
    <polygon points="${edge(1, 16)}"/>
  </g>
  <g fill="url(#neon)">
    <polygon points="${edge(-1, 6)}"/>
    <polygon points="${edge(1, 6)}"/>
  </g>
</svg>
`;
}

const out = __dirname;
fs.writeFileSync(path.join(out, 'road.svg'), roadSvg());
for (let i = 0; i < PHASES; i++) {
  fs.writeFileSync(path.join(out, `lanes-${i}.svg`), lanesSvg(i / PHASES));
}
console.log(`wrote road.svg and lanes-0..${PHASES - 1}.svg`);
